version: '3'
services:
  express-server:
    image: aleksandrskondratjevs/prerender:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://127.0.0.1:6379
      - XDG_RUNTIME_DIR=/tmp/runtime
    depends_on:
      - redis
    network_mode: host


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
